### ISSUE TITLE
error: deployment

### ISSUE THREAD

**Issue by me-ascii** [amino/amino-deploy#2]
Hi. I'm stuck on deploy error.
I'm trying to repeat https://github.com/cpsubrian/amino-nodedc/tree/master/demos/demo-2
I just followed the instructions, update libraries
But when doing
`amino deploy --threads=1 -- node humblr.js` or just `amino deploy`
getting errors:

```
searching for humblr-drone drones...
found 3 drones.
drone j3xCI1ri: deploying...
drone Jtp1onbk: deploying...
drone cEXFej4r: deploying...
Error: drone cEXFej4r: received error on deploy: deployment id in URL must match sha1 sum of payload
...
```

then exit

**Comment by me-ascii** [comment]
Additional info:
`files.payload.hash` is `da39a3ee5e6b4b0d3255bfef95601890afd80709`
but
`req.params.id` is `5f343edfc9273db365d975ddb17843e415531374`

How to make it work? Thanks

**Comment by cpsubrian** [comment]
Just out of curiosity could you post your node, amino-deploy, and amino-drone versions.  I'll see if I can reproduce locally.

Something like this:

```
$ node --version && amino --version && amino-drone --version
v0.8.19
0.1.0
0.1.2
```

**Comment by cpsubrian** [comment]
Confirmed I'm receiving the same error as you. I will try to track down the commit where this started.

**Comment by carlos8f** [comment]
I just followed the demo-2 tutorial and couldn't reproduce the bug, my setup is

```
$ node --version && amino --version && amino-drone --version
v0.8.22
0.1.0
0.1.2
```

**Comment by cpsubrian** [comment]
Will try updating node.

**Comment by me-ascii** [comment]
Currently:
v0.8.17
0.1.0
0.1.2

**Comment by carlos8f** [comment]
I'm pretty sure this is the culprit: https://github.com/felixge/node-formidable/pull/210

I published amino-drone v0.1.3 which includes the fix. @me-ascii , please reopen if you still get the error. Thanks.

**Comment by me-ascii** [comment]
Thx, will try it as soon as possible

**Comment by me-ascii** [comment]
Confirm!
